### ISSUE TITLE
耦合度过高，无法提供外置接口通过tcp或其他连接方式使用

### ISSUE THREAD

**Issue by shihaoH** [qingstor/neonio#3]
现在的neonio仅能通过k8s集群内访问到neonio的存储池，不能通过外置接口插件进行使用。
建议开放一个接口或其他方式能使其他网络或集群能不依赖同一个k8s集群使用neonio的存储功能

**Comment by Hansyangxingxiang** [comment]
已经支持，参考README_zh.md中《应用场景》： https://github.com/qingstor/neonio/blob/main/README_zh.md#%E5%BA%94%E7%94%A8%E5%9C%BA%E6%99%AF
